name: biapy
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - scikit-image
  - pandas
  - ipyvolume
  - pip
  - jupyter
  - jupyter_contrib_nbextensions
  - ipywidgets
  - pyjnius=1.2.0
  - pyimagej
  - openjdk=8
  - plotnine
  - seaborn
  - pip:
    - napari
    - trackpy
    - tqdm
    - mrc
    - aicsimageio