name: biapy2021
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - scikit-image
  - pandas
  - ipyvolume
  - pip
  - voila
  - itkwidgets
  - jupyterlab
  - scikit-learn
  - ipympl
  - ipywidgets
  - pyimagej
  - openjdk=8
  - seaborn
  - plotnine 
  - pip:
    - napari
    - trackpy
    - tensorflow
    - tqdm
    - torch 
    - torchvision
    - mrc
    - stardist
    - cellpose
    - aicsimageio
    - xlrd