name: biapy2021
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - scikit-image
  - pandas
  - pip
  - jupyterlab
  - scikit-learn
  - ipympl
  - ipywidgets
  - pyimagej
  - openjdk=8
  - seaborn
  - plotnine 
  - pip:
    - napari[all]
    - trackpy
    - tqdm
    - mrc
    - cellpose
    - aicsimageio
    - xlrd